[package]
name = "user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth = { git = "https://github.com/Banyc/auth.git", rev = "fd9c32ff8dfb8a454a927ecbd9270525b8e3d1bf" }
blake3 = "1"
rand = "0.8"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["full"] }
